replacements:
  HELMET: "Cute Helmet"
  CHESTPLATE: "OP Chestplate"
  LEGGINGS: "Gucci Leggins"
  BOOTS: "Puss and boots"
  SHIELD: "Escudo"
  SWORD: "Epic Sword"
  BOW: "Fire Bow"
  PICKAXE: "Ice Pickaxe"
  AXE: "Epic Axe"
  SHOVEL: "Nice Shovel"
  HOE: "Epic Hoe"
placeholder: "#990000&lᴠ#a71d1d&lɪ#b63a3a&lᴘ#c45757&l #d37474&lᴘ#e19191&lʟ#f0aeae&lᴜ#ffcccc&lѕ"
format: "&f%item% &b&l➪ &f%placeholder%"
replace-everything: true